name: Build Releases

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check my Repo code
        uses: actions/checkout@v3
      
      - name: Set up JDK 11  
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      
      - name: Flutter Run & Build
        run: flutter pub get
        run: flutter build apk --release -- split-per-abi

      - name: push to release
        uses: ncipollo/release-actions@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v0.0.0+1
          token: ${{ secerts.TOKEN }}
